package cgpa.calculator;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class CgpaSelector extends javax.swing.JFrame {

    /**
     * Creates new form CgpaSelector
     */
    Connection con;

    public CgpaSelector() {
        initComponents();
    }

    public CgpaSelector(String Username) {
        initComponents();
        jLabelUsername.setText(Username);
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/student_Info", "pritom", "190204018");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);

        }
        try {
            // TODO add your handling code here:
            String sql = "SELECT * FROM PRITOM.STUDENT WHERE USER_NAME = '" + jLabelUsername.getText() + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String x = rs.getString("SEMESTER");
                if (x.equals("1.1")) {
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1.1"}));

                } else if (x.equals("1.2")) {
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1.1", "1.2"}));

                } else if (x.equals("2.1")) {
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1.1", "1.2", "2.1"}));

                } else if (x.equals("2.2")) {
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1.1", "1.2", "2.1", "2.2"}));

                } else if (x.equals("3.1")) {
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1.1", "1.2", "2.1", "2.2", "3.1"}));

                } else if (x.equals("3.2")) {
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1.1", "1.2", "2.1", "2.2", "3.1", "3.2"}));

                } else if (x.equals("4.1")) {
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1.1", "1.2", "2.1", "2.2", "3.1", "3.2", "4.1"}));

                } else if (x.equals("4.2")) {
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1.1", "1.2", "2.1", "2.2", "3.1", "3.2", "4.1", "4.2"}));

                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Wrong Username or Password", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonGenerate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select CGPA");
        setLocation(new java.awt.Point(700, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select your semester from the options given below");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.1", "1.2", "2.1", "2.2", "3.1", "3.2", "4.1", "4.2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("1.1");

        jButtonGenerate.setText("Generate CGPA");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selected Semester");

        jLabelUsername.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit)
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButtonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonExit))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String x = jComboBox1.getSelectedItem().toString();
        //jComboBox1.set
        jLabel2.setText(x);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().toString().equals("1.1")) {
            String x = jLabelUsername.getText();
            dispose();
            sem1_1 s1 = new sem1_1(x);
            s1.show();
        } else if (jComboBox1.getSelectedItem().toString().equals("1.2")) {
            String x = jLabelUsername.getText();
            dispose();
            sem1_2 s1 = new sem1_2(x);
            s1.show();
        } else if (jComboBox1.getSelectedItem().toString().equals("2.1")) {
            String x = jLabelUsername.getText();
            dispose();
            sem2_1 s1 = new sem2_1(x);
            s1.show();
        }else if (jComboBox1.getSelectedItem().toString().equals("2.2")) {
            String x = jLabelUsername.getText();
            dispose();
            sem2_2 s1 = new sem2_2(x);
            s1.show();
        }else if (jComboBox1.getSelectedItem().toString().equals("3.1")) {
            String x = jLabelUsername.getText();
            dispose();
            sem3_1 s1 = new sem3_1(x);
            s1.show();
        }else if (jComboBox1.getSelectedItem().toString().equals("3.2")) {
            String x = jLabelUsername.getText();
            dispose();
            sem3_2 s1 = new sem3_2(x);
            s1.show();
        }else if (jComboBox1.getSelectedItem().toString().equals("4.1")) {
            String x = jLabelUsername.getText();
            dispose();
            sem4_1 s1 = new sem4_1(x);
            s1.show();
        }else if (jComboBox1.getSelectedItem().toString().equals("4.2")) {
            String x = jLabelUsername.getText();
            dispose();
            sem4_2 s1 = new sem4_2(x);
            s1.show();
        }
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            String sql = "SELECT * FROM PRITOM.STUDENT WHERE USER_NAME = '" + jLabelUsername.getText() + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String x = rs.getString("NAME");
                dispose();
                Welcome wc = new Welcome(x, jLabelUsername.getText());
                wc.show();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Wrong Username or Password", "Error", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CgpaSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CgpaSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CgpaSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CgpaSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CgpaSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelUsername;
    // End of variables declaration//GEN-END:variables
}
