/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cgpa.calculator;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    Connection con;

    public Edit() {
        initComponents();
    }

    public Edit(String username) {
        initComponents();
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/student_Info", "pritom", "190204018");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);

        }
        jLabelUsername.setText(username);
        jButtonPWOK.setEnabled(false);
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        jLabel3.setEnabled(false);
        jPasswordFieldNP.setEnabled(false);
        jPasswordFieldOP.setEnabled(false);
        jPasswordFieldRENP.setEnabled(false);
    }

    void update11() {
        try {
            String un = jLabelUsername.getText();
            String sql = "DELETE FROM PRITOM.INFO11 (USERNAME) VALUES ('" + un + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void update12() {
        try {
            String un = jLabelUsername.getText();
            String sql = "DELETE FROM PRITOM.INFO12 (USERNAME) VALUES ('" + un + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void update21() {
        try {
            String un = jLabelUsername.getText();
            String sql = "DELETE FROM PRITOM.INFO21 (USERNAME) VALUES ('" + un + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void update22() {
        try {
            String un = jLabelUsername.getText();
            String sql = "DELETE FROM PRITOM.INFO22 (USERNAME) VALUES ('" + un + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void update31() {
        try {
            String un = jLabelUsername.getText();
            String sql = "DELETE FROMPRITOM.INFO31 (USERNAME) VALUES ('" + un + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void update32() {
        try {
            String un = jLabelUsername.getText();
            String sql = "DELETE FROM PRITOM.INFO32 (USERNAME) VALUES ('" + un + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);

        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void update41() {
        try {
            String un = jLabelUsername.getText();
            String sql = "DELETE FROM PRITOM.INFO41 (USERNAME) VALUES ('" + un + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void update42() {
        try {
            String un = jLabelUsername.getText();
            String sql = "DELETE FROM PRITOM.INFO42 (USERNAME) VALUES ('" + un + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsername = new javax.swing.JLabel();
        jButtonPW = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldOP = new javax.swing.JPasswordField();
        jPasswordFieldNP = new javax.swing.JPasswordField();
        jPasswordFieldRENP = new javax.swing.JPasswordField();
        jButtonPWOK = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Profile");
        setLocation(new java.awt.Point(700, 300));

        jLabelUsername.setText("Username");

        jButtonPW.setText("Edit Password");
        jButtonPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPWActionPerformed(evt);
            }
        });

        jLabel1.setText("Old Password :");

        jLabel2.setText("New Password :");

        jLabel3.setText("Re-Enter New Password: ");

        jButtonPWOK.setText("Update");
        jButtonPWOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPWOKActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButtonPW, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordFieldRENP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldNP)
                            .addComponent(jPasswordFieldOP))
                        .addGap(27, 27, 27)
                        .addComponent(jButtonPWOK)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordFieldOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPWOK, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldRENP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPWActionPerformed
        // TODO add your handling code here:
        jButtonPW.setEnabled(false);
        jButtonPWOK.setEnabled(true);
        jPasswordFieldNP.setEnabled(true);
        jPasswordFieldOP.setEnabled(true);
        jPasswordFieldRENP.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
    }//GEN-LAST:event_jButtonPWActionPerformed

    private void jButtonPWOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPWOKActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String username = jLabelUsername.getText();
            String password = jPasswordFieldOP.getText();
            String sql = "SELECT * FROM PRITOM.STUDENT WHERE USER_NAME = '" + username + "' AND PASSWORD = '" + password + "'";
            Statement st = con.createStatement();
            //row = st.executeUpdate(sql);
            ResultSet rs = st.executeQuery(sql);
            //System.out.println(row);
            if (rs.next()) {
                if (jPasswordFieldNP.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "New password cant be empty", "update info", JOptionPane.INFORMATION_MESSAGE);
                } else if (!jPasswordFieldNP.getText().equals(jPasswordFieldRENP.getText())) {
                    JOptionPane.showMessageDialog(null, "New password doesnt match", "update info", JOptionPane.INFORMATION_MESSAGE);
                } //JOptionPane.showMessageDialog(null, "Signed in succesfully", "Sign in", JOptionPane.INFORMATION_MESSAGE);
                else {
                    sql = "UPDATE PRITOM.STUDENT SET \"PASSWORD\" = '" + jPasswordFieldRENP.getText() + "' WHERE USER_NAME = '" + username + "'";
                    //String sql = "UPDATE PRITOM.INFO11 SET \"CSE1101\" = 'A' WHERE USERNAME = '190204018'";
                    st = con.createStatement();
                    st.executeUpdate(sql);
                    jButtonPW.setEnabled(true);
                    jButtonPWOK.setEnabled(false);
                    jPasswordFieldNP.setEnabled(false);
                    jPasswordFieldOP.setEnabled(false);
                    jPasswordFieldRENP.setEnabled(false);
                    jLabel1.setEnabled(false);
                    jLabel2.setEnabled(false);
                    jLabel3.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Password updated", "Update info", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                jPasswordFieldOP.setText("");
                JOptionPane.showMessageDialog(null, "Wrong Password", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPWOKActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String username = jLabelUsername.getText();
            String sql = "SELECT * FROM PRITOM.STUDENT WHERE USER_NAME = '" + username + "'";
            Statement st = con.createStatement();
            //row = st.executeUpdate(sql);
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                //JOptionPane.showMessageDialog(null, "Signed in succesfully", "Sign in", JOptionPane.INFORMATION_MESSAGE);

                String x = rs.getString("NAME");
                dispose();
                Welcome wc = new Welcome(x, username);
                wc.show();
            }
        } catch (SQLException ex) {
            Logger.getLogger(sem1_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Info", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonPW;
    private javax.swing.JButton jButtonPWOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordFieldNP;
    private javax.swing.JPasswordField jPasswordFieldOP;
    private javax.swing.JPasswordField jPasswordFieldRENP;
    // End of variables declaration//GEN-END:variables
}
